### ISSUE TITLE
Mixed content error

### ISSUE THREAD

**Issue by Flobbah** [Manliketjb/QBCore-Lottoscript#1]
Hi,
in nui/js/index.js line 92 to set https instead of http.
`$.post('http://lotto/win', JSON.stringify({}));2`
whatever the 2 is for, i guess thats not ment do be there?
so it would look like this if im correct:
`$.post('https://lotto/win', JSON.stringify({}));`
![disnutz](https://user-images.githubusercontent.com/41282555/136434897-3c46c7f9-af73-4580-861b-a957ea6a3933.PNG)

**Comment by Manliketjb** [comment]
thanks for the reminder, forgot to update it earlier. I'm currently getting the issue where winning doesn't pay out if you know how to fix that?
